# Generated by Django 4.2.7 on 2023-12-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_News_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_news_order_name', models.CharField(max_length=50, verbose_name='Nombre_Estado_Novedades_Pedido')),
            ],
            options={
                'verbose_name': 'Estado_Novedad_Pedido',
                'verbose_name_plural': 'Estado_Novedades_Pedidos',
                'db_table': 'estnovedadespedidoprov',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateField(verbose_name='Fecha_Pedido')),
                ('product_quantity', models.IntegerField(verbose_name='Cantidad_Producto')),
                ('order_price', models.PositiveIntegerField(verbose_name='Precio_Pedido')),
                ('deliver_date', models.DateField(verbose_name='Fecha_Entrega')),
                ('address', models.CharField(max_length=255, verbose_name='Direccion')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venta.product')),
            ],
            options={
                'verbose_name': 'Pedido_Proveedor',
                'verbose_name_plural': 'Pedido_Proveedores',
                'db_table': 'pedido_proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier_Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_order_status_name', models.CharField(max_length=255, verbose_name='Nombre_Estado_Pedido_Proveedor')),
            ],
            options={
                'verbose_name': 'Estado_Pedido_Proveedor',
                'verbose_name_plural': 'Estado_Pedidos_Proveedores',
                'db_table': 'estadopedidoprov',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='Nombre_Proveedor')),
                ('supplier_address', models.CharField(max_length=255, verbose_name='Direccion_Proveedor')),
                ('supplier_email', models.CharField(max_length=255, verbose_name='Email_Proveedor')),
                ('supplier_nit', models.CharField(max_length=20, verbose_name='Nit_Proveedor')),
                ('supplier_cellphone', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier_Order_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_new_order_supplier', models.DateTimeField(verbose_name='Nombre_Proveedor')),
                ('status_news_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.status_news_order')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.supplier_order')),
            ],
            options={
                'verbose_name': 'Novedades_Pedido_Proveedor',
                'verbose_name_plural': 'Novedades_Pedido_Proveedores',
                'db_table': 'novedadespedidoproveedor',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='supplier_order',
            name='supplier_order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.supplier_order_status'),
        ),
        migrations.AddField(
            model_name='supplier_order',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.suppliers'),
        ),
    ]
