# Generated by Django 4.2.7 on 2023-12-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type_name', models.CharField(max_length=50, verbose_name='Nombre_Tipo_Flujo')),
            ],
            options={
                'verbose_name': 'Tipo_Flujo',
                'verbose_name_plural': 'Tipos_Flujos',
                'db_table': 'tipoflujo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory_Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.flow_type')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product')),
            ],
            options={
                'verbose_name': 'Flujo_Inventario',
                'verbose_name_plural': 'Flujos_Inventarios',
                'db_table': 'flujoinventario',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Nombre_Categoria')),
                ('description_category', models.CharField(max_length=50, verbose_name='Descripcion_Categoria')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
                'ordering': ['id'],
            },
        ),
    ]
