# Generated by Django 4.2.7 on 2023-12-09 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_state_name', models.CharField(max_length=50, verbose_name='Nombre_Estado_Servicio')),
            ],
            options={
                'verbose_name': 'Estado_Servicio',
                'verbose_name_plural': 'Estado_Servicios',
                'db_table': 'estadoservicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_name', models.CharField(max_length=50, verbose_name='Nombre_Tipo_Servicio')),
            ],
            options={
                'verbose_name': 'Tipo_Servicio',
                'verbose_name_plural': 'Tipo_Servicios',
                'db_table': 'tiposervicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(max_length=50, verbose_name='Descripcion_Servicio')),
                ('service_price', models.PositiveIntegerField(verbose_name='Precio_Servicio')),
                ('service_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicioTecnico.service_status')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicioTecnico.service_type')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_description', models.TextField(max_length=50, verbose_name='Descripcion_Agendamiento')),
                ('scheduling_time', models.TimeField(verbose_name='Hora_Agendamiento')),
                ('scheduling_date', models.DateField(verbose_name='Fecha_Agendamiento')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicioTecnico.service')),
            ],
            options={
                'verbose_name': 'Agendamiento',
                'verbose_name_plural': 'Agendamientos',
                'db_table': 'agendamiento',
                'ordering': ['id'],
            },
        ),
    ]
