# Generated by Django 4.2.7 on 2023-12-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_warranty_options_alter_warranty_type_options_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='flow_type',
            options={'ordering': ['id'], 'verbose_name': 'Tipo_Flujo', 'verbose_name_plural': 'Tipos Flujos'},
        ),
        migrations.AlterModelOptions(
            name='inventory_flow',
            options={'ordering': ['id'], 'verbose_name': 'Flujo Inventario', 'verbose_name_plural': 'Flujos Inventarios'},
        ),
        migrations.AddField(
            model_name='flow_type',
            name='flow_type_description',
            field=models.TextField(max_length=50, null=True, verbose_name='Descripción Tipo Flujo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, verbose_name='Nombre Categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_category',
            field=models.CharField(max_length=50, verbose_name='Descripción Categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='flow_type',
            name='flow_type_name',
            field=models.CharField(max_length=50, verbose_name='Nombre Tipo Flujo'),
        ),
        migrations.AlterField(
            model_name='inventory_flow',
            name='flow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.flow_type', verbose_name='Tipo Flujo'),
        ),
        migrations.AlterField(
            model_name='inventory_flow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product', verbose_name='Producto'),
        ),
    ]
