# Generated by Django 4.2.7 on 2023-12-11 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_category_options_alter_flow_type_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
