# Generated by Django 4.2.6 on 2023-11-08 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_warranty_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='Nombre_Producto')),
                ('product_description', models.TextField(max_length=50, verbose_name='Descripcion_Producto')),
                ('product_reference', models.CharField(max_length=50, verbose_name='Referencia_Producto')),
                ('product_value', models.PositiveIntegerField(verbose_name='Valor_Producto')),
                ('product_quantity', models.IntegerField(verbose_name='Cantida_Producto')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.brand')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
    ]
