# Generated by Django 4.2.6 on 2023-11-22 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(verbose_name='Cantidad_Producto'),
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_description', models.TextField(max_length=50, verbose_name='Descripcion_Garantía')),
                ('warranty_time', models.TimeField(verbose_name='Time_Garantía')),
                ('warranty_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.warranty_type')),
            ],
            options={
                'verbose_name': 'Garantia',
                'verbose_name_plural': 'Garantias',
                'db_table': 'garantia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_Date', models.DateTimeField(verbose_name='Fecha_Venta')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.PositiveIntegerField(verbose_name='Precio')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('vat', models.PositiveIntegerField(verbose_name='Iva')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.product')),
                ('warranty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.warranty')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
    ]
