# Generated by Django 4.2.7 on 2023-12-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_customer_order_status_sale_employee_customer_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.PositiveIntegerField(editable=False, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveIntegerField(editable=False, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vat',
            field=models.PositiveIntegerField(editable=False, verbose_name='Iva'),
        ),
    ]
