# Generated by Django 4.2.7 on 2023-12-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_sale_subtotal_alter_sale_total_alter_sale_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.PositiveIntegerField(verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='vat',
            field=models.PositiveIntegerField(verbose_name='Iva'),
        ),
    ]
