# Generated by Django 5.0 on 2023-12-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_rename_sale_date_sale_sale_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='warranty_time',
            field=models.DateField(verbose_name='Tiempo_Garantía'),
        ),
    ]
