# Generated by Django 4.2.7 on 2023-12-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicioTecnico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service_status',
            options={'ordering': ['id'], 'verbose_name': 'Estado Servicio', 'verbose_name_plural': 'Estado Servicios'},
        ),
        migrations.AlterModelOptions(
            name='service_type',
            options={'ordering': ['id'], 'verbose_name': 'Tipo Servicio', 'verbose_name_plural': 'Tipo Servicios'},
        ),
        migrations.RemoveField(
            model_name='service_status',
            name='service_state_name',
        ),
        migrations.AddField(
            model_name='service_status',
            name='service_status_description',
            field=models.TextField(max_length=50, null=True, verbose_name='Descripción Estado Servicio'),
        ),
        migrations.AddField(
            model_name='service_status',
            name='service_status_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre Estado Servicio'),
        ),
        migrations.AddField(
            model_name='service_type',
            name='service_type_description',
            field=models.TextField(max_length=50, null=True, verbose_name='Descripción Tipo Servicio'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_date',
            field=models.DateField(verbose_name='Fecha Agendamiento'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_description',
            field=models.TextField(max_length=50, verbose_name='Descripción Agendamiento'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_time',
            field=models.TimeField(verbose_name='Hora Agendamiento'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicioTecnico.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(max_length=50, verbose_name='Descripción Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.PositiveIntegerField(verbose_name='Precio Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicioTecnico.service_status', verbose_name='Estado Servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicioTecnico.service_type', verbose_name='Tipo Servicio'),
        ),
        migrations.AlterField(
            model_name='service_type',
            name='service_type_name',
            field=models.CharField(max_length=50, verbose_name='Nombre Tipo Servicio'),
        ),
    ]
