# Generated by Django 4.2.7 on 2023-12-09 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registroUsuario', '0003_cargo_ciudad_especialidadcargo_estadodisponibilidad_and_more'),
        ('servicioTecnico', '0002_alter_service_status_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='estado_disponibilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.estadodisponibilidad'),
        ),
        migrations.AddField(
            model_name='service',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
