# Generated by Django 4.2.7 on 2023-12-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0004_availability_status_city_client_client_type_contact_and_more'),
        ('servicioTecnico', '0003_scheduling_empleado_scheduling_estado_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduling',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='scheduling',
            name='estado_disponibilidad',
        ),
        migrations.RemoveField(
            model_name='service',
            name='cliente',
        ),
        migrations.AddField(
            model_name='scheduling',
            name='availability_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.availability_status', verbose_name='Estado Disponibilidad'),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cliente', to='registroUsuario.client', verbose_name='Cliente'),
        ),
    ]
