# Generated by Django 4.2.7 on 2023-11-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
        ('ordencompra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_order',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venta.product'),
        ),
    ]
