# Generated by Django 4.2.7 on 2023-12-09 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0002_alter_customuser_second_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('descripcion_cargo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EspecialidadCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especialidad_cargo', models.CharField(max_length=100, null=True)),
                ('descripcion_especialidad_cargo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_disponibilidad', models.CharField(max_length=100)),
                ('descripcion_tipo_disponibilidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=100)),
                ('descripcion_rol', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TiempoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tiempo_trabajo', models.CharField(max_length=100)),
                ('descripcion_tiempo_trabajo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo_cliente', models.CharField(max_length=100)),
                ('descripcion_tipo_cliente', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_identificacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.cargo')),
                ('estado_disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.estadodisponibilidad')),
                ('tiempo_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.tiempotrabajo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.tipocliente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.especialidadcargo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contacto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.contacto'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(blank=True, to='registroUsuario.rol'),
        ),
    ]
