# Generated by Django 4.2.7 on 2023-12-10 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicioTecnico', '0004_remove_scheduling_empleado_and_more'),
        ('registroUsuario', '0004_availability_status_city_client_client_type_contact_and_more'),
        ('ordencompra', '0005_supplier_order_employee_supplier_order_news_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoDisponibilidad',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.DeleteModel(
            name='TiempoTrabajo',
        ),
        migrations.DeleteModel(
            name='TipoCliente',
        ),
        migrations.AddField(
            model_name='position',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.position_specialty', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='employee',
            name='availability_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.availability_status', verbose_name='Estado Disponibilidad'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.position', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.time_work', verbose_name='Tiempo Trabajo'),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.city', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.client_type', verbose_name='Tipo Cliente'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.contact'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ManyToManyField(blank=True, to='registroUsuario.role'),
        ),
    ]
