# Generated by Django 4.2.7 on 2023-12-10 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0006_alter_availability_status_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availability_status',
            table='registrousuario_availability_status',
        ),
        migrations.AlterModelTable(
            name='city',
            table='registrousuario_city',
        ),
        migrations.AlterModelTable(
            name='client',
            table='registrousuario_client',
        ),
        migrations.AlterModelTable(
            name='client_type',
            table='registrousuario_client_type',
        ),
        migrations.AlterModelTable(
            name='contact',
            table='registrousuario_contact',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='registrousuario_employee',
        ),
        migrations.AlterModelTable(
            name='position',
            table='registrousuario_position',
        ),
        migrations.AlterModelTable(
            name='position_specialty',
            table='registrousuario_position_specialty',
        ),
        migrations.AlterModelTable(
            name='role',
            table='registrousuario_role',
        ),
        migrations.AlterModelTable(
            name='time_work',
            table='registrousuario_time_work',
        ),
    ]
