# Generated by Django 4.2.7 on 2023-12-11 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0007_alter_availability_status_table_alter_city_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_type', models.CharField(max_length=100, verbose_name='Tipo Identificación')),
                ('description_type_identification', models.TextField(max_length=100, verbose_name='Descripción Tipo Identificación')),
            ],
            options={
                'verbose_name': 'Tipo Identificación',
                'verbose_name_plural': 'Tipos Identificaciones',
                'db_table': 'registrousuario_identification_type',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.ForeignKey(max_length=12, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.contact', verbose_name='Contacto'),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='identification_type',
            field=models.ForeignKey(max_length=12, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.identification_type', verbose_name='Tipo Identifiacion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.role', verbose_name='Rol'),
        ),
    ]
