# Generated by Django 4.2.7 on 2023-12-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0009_remove_position_position_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='specialty',
        ),
    ]
