# Generated by Django 4.2.7 on 2023-12-11 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registroUsuario', '0010_remove_position_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='position_specialty',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.position', verbose_name='Cargo'),
        ),
    ]
