# Generated by Django 4.2.7 on 2023-12-09 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_warranty_options_alter_warranty_type_options_and_more'),
        ('ordencompra', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status_news_order',
            options={'ordering': ['id'], 'verbose_name': 'Estado Novedad Pedido', 'verbose_name_plural': 'Estado Novedades Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='supplier_order',
            options={'ordering': ['id'], 'verbose_name': 'Pedido Proveedor', 'verbose_name_plural': 'Pedido Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='supplier_order_news',
            options={'ordering': ['id'], 'verbose_name': 'Novedades Pedido Proveedor', 'verbose_name_plural': 'Novedades Pedido Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='supplier_order_status',
            options={'ordering': ['id'], 'verbose_name': 'Estado Pedido Proveedor', 'verbose_name_plural': 'Estado Pedidos Proveedores'},
        ),
        migrations.AddField(
            model_name='status_news_order',
            name='status_news_order_description',
            field=models.TextField(max_length=50, null=True, verbose_name='Descripción Tipo Novedad Pedido'),
        ),
        migrations.AddField(
            model_name='supplier_order_status',
            name='supplier_order_status_description',
            field=models.TextField(max_length=50, null=True, verbose_name='Descripción Tipo Estado Pedido Proveedor'),
        ),
        migrations.AlterField(
            model_name='status_news_order',
            name='status_news_order_name',
            field=models.CharField(max_length=50, verbose_name='Nombre Estado Novedades Pedido'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='date_order',
            field=models.DateField(verbose_name='Fecha Pedido'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='deliver_date',
            field=models.DateField(verbose_name='Fecha Entrega'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='order_price',
            field=models.PositiveIntegerField(verbose_name='Precio Pedido'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venta.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='product_quantity',
            field=models.IntegerField(verbose_name='Cantidad Producto'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='supplier_order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.supplier_order_status', verbose_name='Estado Orden Proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier_order',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.suppliers', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier_order_news',
            name='date_new_order_supplier',
            field=models.DateTimeField(verbose_name='Nombre Proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier_order_news',
            name='status_news_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.status_news_order', verbose_name='Estado Novedades Pedido'),
        ),
        migrations.AlterField(
            model_name='supplier_order_news',
            name='supplier_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordencompra.supplier_order', verbose_name='Orden Pedido Proveedor'),
        ),
        migrations.AlterField(
            model_name='supplier_order_status',
            name='supplier_order_status_name',
            field=models.CharField(max_length=255, verbose_name='Nombre Estado Pedido Proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_address',
            field=models.CharField(max_length=255, verbose_name='Dirección Proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_cellphone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular Proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_email',
            field=models.CharField(max_length=255, verbose_name='Email Proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.CharField(max_length=50, verbose_name='Nombre Proveedor'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_nit',
            field=models.CharField(max_length=20, verbose_name='Nit Proveedor'),
        ),
    ]
