# Generated by Django 4.2.7 on 2023-12-09 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registroUsuario', '0003_cargo_ciudad_especialidadcargo_estadodisponibilidad_and_more'),
        ('ordencompra', '0002_alter_status_news_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_order',
            name='especialidad_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.especialidadcargo'),
        ),
        migrations.AddField(
            model_name='supplier_order',
            name='estado_disponibilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.estadodisponibilidad'),
        ),
        migrations.AddField(
            model_name='supplier_order_news',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Empleado'),
        ),
    ]
