# Generated by Django 4.2.7 on 2023-12-10 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0003_supplier_order_especialidad_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_order',
            name='especialidad_cargo',
        ),
        migrations.RemoveField(
            model_name='supplier_order',
            name='estado_disponibilidad',
        ),
        migrations.RemoveField(
            model_name='supplier_order_news',
            name='empleado',
        ),
    ]
