# Generated by Django 4.2.7 on 2023-12-10 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0004_remove_supplier_order_especialidad_cargo_and_more'),
        ('registroUsuario', '0004_availability_status_city_client_client_type_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier_order',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.employee', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='supplier_order_news',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registroUsuario.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='supplier_order_news',
            name='date_new_order_supplier',
            field=models.DateTimeField(verbose_name='Fecha Novedades Pedido Proveedor'),
        ),
    ]
