# Generated by Django 4.2.7 on 2023-12-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordencompra', '0005_supplier_order_employee_supplier_order_news_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_order',
            name='date_order',
            field=models.DateTimeField(verbose_name='Fecha Pedido'),
        ),
    ]
